USE MASTER;
GO

-- This is needed to make sure that the database is not in use when we try to delete it.
IF DB_ID('WHITEROCK_POLES') IS NOT NULL
ALTER DATABASE WHITEROCK_POLES
SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO

DROP DATABASE IF EXISTS WHITEROCK_POLES
GO

CREATE DATABASE WHITEROCK_POLES;
GO

USE WHITEROCK_POLES;
GO

CREATE TABLE DEPARTMENT (
DPT_CODE NUMERIC(3) PRIMARY KEY,
DPT_NAME VARCHAR(255) NOT NULL);
GO

CREATE TABLE EMPLOYEE (
EMP_ID NUMERIC(4) PRIMARY KEY,
EMP_JOB_TITLE VARCHAR(50),
EMP_FNAME VARCHAR(30) NOT NULL,
EMP_LNAME VARCHAR(30) NOT NULL,
EMP_PNUM CHAR(12) CHECK (EMP_PNUM like '[0-9][0-9][0-9]-[0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]'),
DPT_CODE NUMERIC(3) FOREIGN KEY REFERENCES DEPARTMENT(DPT_CODE) NOT NULL,
EMP_TYPE CHAR(3) CHECK(EMP_TYPE IN ('MGR','ENG', 'PLN', 'FTC')) NOT NULL);
GO

CREATE TABLE DEPARTMENT_MANAGER (
EMP_ID NUMERIC(4) PRIMARY KEY FOREIGN KEY REFERENCES EMPLOYEE(EMP_ID),
MGR_START_DATE DATE DEFAULT SYSDATETIME() NOT NULL,
MGR_END_DATE DATE);
GO

CREATE TABLE PLANNER (
EMP_ID NUMERIC(4) PRIMARY KEY FOREIGN KEY REFERENCES EMPLOYEE(EMP_ID),
PLN_DISCIPLINE VARCHAR(30));
GO

CREATE TABLE ENGINEER (
EMP_ID NUMERIC(4) PRIMARY KEY FOREIGN KEY REFERENCES EMPLOYEE(EMP_ID),
ENG_DISCIPLINE VARCHAR(30));
GO

CREATE TABLE FIELD_TECHNICIAN (
EMP_ID NUMERIC(4) PRIMARY KEY FOREIGN KEY REFERENCES EMPLOYEE(EMP_ID),
FTC_AREA VARCHAR(30));
GO

CREATE TABLE POLE (
POLE_ID NUMERIC(8) PRIMARY KEY,
POLE_IS_LIGHT_POLE BIT NOT NULL,
POLE_IS_TRAFFIC_POLE BIT NOT NULL,
POLE_COMMENTS VARCHAR(255),
POLE_LAST_INSPECTION_DATE DATE,
POLE_HEIGHT NUMERIC(3, 1),
POLE_COLOUR VARCHAR(20),
POLE_REPAINT_DATE DATE,
POLE_INSTALL_DATE DATE NOT NULL,
POLE_REMOVED BIT NOT NULL,
POLE_LIGHT_TYPE VARCHAR(3),
POLE_BULB_TYPE VARCHAR(3),
POLE_WATTAGE NUMERIC(4),
POLE_RELAMP_DATE DATE,
POLE_HOUSE_NUM NUMERIC(4),
POLE_STREET VARCHAR(50),
POLE_FOUNDATION VARCHAR(30),
POLE_HAS_FUSE BIT,
POLE_ROAD_TYPE CHAR(1),
POLE_NEAR_BUS_STOP BIT,
POLE_NEAR_SCHOOL BIT,
POLE_NEAR_PARK BIT,
POLE_NEAR_SIDEWALK BIT,
POLE_HAS_BANNER_ARMS BIT,
POLE_X_COORD NUMERIC(8,5) NOT NULL,
POLE_Y_COORD NUMERIC(8,5) NOT NULL
);
GO

CREATE TABLE TRAFFIC_POLE (
POLE_ID NUMERIC(8) PRIMARY KEY FOREIGN KEY REFERENCES POLE (POLE_ID),
POLE_PUSH_BUTTON BIT,
POLE_SIGNAL_DIRECTION VARCHAR(2),
POLE_SIGNAGE VARCHAR(30),
);
GO

CREATE TABLE LIGHT_POLE (
POLE_ID NUMERIC(8) PRIMARY KEY FOREIGN KEY REFERENCES POLE (POLE_ID),
POLE_STYLE VARCHAR(30),
POLE_LUMINAIR_STYLE VARCHAR(30),
POLE_BASE_COLLAR BIT,
);
GO

CREATE TABLE INSPECTION_REPORT (
REP_NUM NUMERIC(8) PRIMARY KEY,
EMP_ID NUMERIC(4) FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID),
POLE_ID NUMERIC(8) FOREIGN KEY (POLE_ID) REFERENCES POLE(POLE_ID),
REP_DATE DATE DEFAULT SYSDATETIME() NOT NULL,
REP_NOTES VARCHAR(255),
REP_TYPE VARCHAR(50) NOT NULL,
REP_HAMMER_TEST NUMERIC(2) CHECK (REP_HAMMER_TEST >= 0 AND REP_HAMMER_TEST <= 99),
REP_POLE_CONDITION NUMERIC(1) CHECK (REP_POLE_CONDITION >= 1 AND REP_POLE_CONDITION <= 4),
REP_BASE_COLLAR_CONDITION NUMERIC(1) CHECK (REP_BASE_COLLAR_CONDITION >= 1 AND REP_BASE_COLLAR_CONDITION <= 4),
REP_ANCHOR_BOLTS CHAR(4) CHECK(REP_ANCHOR_BOLTS IN ('POOR', 'GOOD')),
REP_WIRING_CONDITION NUMERIC(1) CHECK (REP_WIRING_CONDITION >= 1 AND REP_WIRING_CONDITION <= 4),
REP_FUSE_CHECK BIT,
REP_BONDED_CONDITION BIT,
REP_REPAIR_RECOMMEND BIT NOT NULL,
REP_REPAIR_SEVERITY NUMERIC(1) CHECK (REP_REPAIR_SEVERITY >= 1 AND REP_REPAIR_SEVERITY <= 4)
);
GO

ALTER TABLE DEPARTMENT
ADD MGR_ID NUMERIC(4) FOREIGN KEY REFERENCES DEPARTMENT_MANAGER(EMP_ID)
GO

--Procedures
CREATE PROCEDURE INSERT_EMPLOYEE
@EMP_ID NUMERIC(4),
@EMP_JOB_TITLE VARCHAR(50),
@EMP_FNAME VARCHAR(30),
@EMP_LNAME VARCHAR(30),
@EMP_PNUM CHAR(12),
@DPT_CODE NUMERIC(3),
@EMP_TYPE CHAR(3)
AS
BEGIN
INSERT INTO EMPLOYEE VALUES (@EMP_ID, @EMP_JOB_TITLE, @EMP_FNAME, @EMP_LNAME, @EMP_PNUM, @DPT_CODE, @EMP_TYPE);
END
GO

CREATE PROCEDURE INSERT_ENGINEER
@EMP_ID NUMERIC(4),
@EMP_JOB_TITLE VARCHAR(50),
@EMP_FNAME VARCHAR(30),
@EMP_LNAME VARCHAR(30),
@EMP_PNUM CHAR(12),
@DPT_CODE NUMERIC(3),
@EMP_TYPE CHAR(3),
@ENG_DISCIPLINE VARCHAR(30)
AS
BEGIN
EXEC INSERT_EMPLOYEE
@EMP_ID,
@EMP_JOB_TITLE,
@EMP_FNAME,
@EMP_LNAME,
@EMP_PNUM,
@DPT_CODE,
@EMP_TYPE;
INSERT INTO ENGINEER VALUES (@EMP_ID, @ENG_DISCIPLINE);
END
GO

CREATE PROCEDURE INSERT_PLANNER
@EMP_ID NUMERIC(4),
@EMP_JOB_TITLE VARCHAR(50),
@EMP_FNAME VARCHAR(30),
@EMP_LNAME VARCHAR(30),
@EMP_PNUM CHAR(12),
@DPT_CODE NUMERIC(3),
@EMP_TYPE CHAR(3),
@PLN_DISCIPLINE VARCHAR(30)
AS
BEGIN
EXEC INSERT_EMPLOYEE
@EMP_ID,
@EMP_JOB_TITLE,
@EMP_FNAME,
@EMP_LNAME,
@EMP_PNUM,
@DPT_CODE,
@EMP_TYPE
INSERT INTO PLANNER VALUES (@EMP_ID, @PLN_DISCIPLINE);
END
GO

CREATE PROCEDURE INSERT_FIELD_TECHNICIAN
@EMP_ID NUMERIC(4),
@EMP_JOB_TITLE VARCHAR(50),
@EMP_FNAME VARCHAR(30),
@EMP_LNAME VARCHAR(30),
@EMP_PNUM CHAR(12),
@DPT_CODE NUMERIC(3),
@EMP_TYPE CHAR(3),
@FTC_AREA VARCHAR(30)
AS
BEGIN
EXEC INSERT_EMPLOYEE
@EMP_ID,
@EMP_JOB_TITLE,
@EMP_FNAME,
@EMP_LNAME,
@EMP_PNUM,
@DPT_CODE,
@EMP_TYPE;
INSERT INTO FIELD_TECHNICIAN VALUES (@EMP_ID, @FTC_AREA);
END
GO

CREATE PROCEDURE INSERT_DEPARTMENT_MANAGER
@EMP_ID NUMERIC(4),
@EMP_JOB_TITLE VARCHAR(50),
@EMP_FNAME VARCHAR(30),
@EMP_LNAME VARCHAR(30),
@EMP_PNUM CHAR(12),
@DPT_CODE NUMERIC(3),
@EMP_TYPE CHAR(3),
@MGR_START_DATE DATE,
@MGR_END_DATE DATE
AS
BEGIN
EXEC INSERT_EMPLOYEE
@EMP_ID,
@EMP_JOB_TITLE,
@EMP_FNAME,
@EMP_LNAME,
@EMP_PNUM,
@DPT_CODE,
@EMP_TYPE
IF @MGR_START_DATE IS NULL
BEGIN
INSERT INTO DEPARTMENT_MANAGER (EMP_ID, MGR_END_DATE)
VALUES (@EMP_ID, @MGR_END_DATE)
END
ELSE
BEGIN
INSERT INTO DEPARTMENT_MANAGER VALUES(@EMP_ID, @MGR_END_DATE, @MGR_START_DATE);
END
END
GO

CREATE PROCEDURE INSERT_POLE
@POLE_ID NUMERIC(8),
@POLE_IS_LIGHT_POLE BIT,
@POLE_IS_TRAFFIC_POLE BIT,
@POLE_COMMENTS VARCHAR(255),
@POLE_LAST_INSPECTION_DATE DATE,
@POLE_HEIGHT NUMERIC(3, 1),
@POLE_COLOUR VARCHAR(20),
@POLE_REPAINT_DATE DATE,
@POLE_INSTALL_DATE DATE,
@POLE_REMOVED BIT,
@POLE_LIGHT_TYPE VARCHAR(3),
@POLE_BULB_TYPE VARCHAR(3),
@POLE_WATTAGE NUMERIC(4),
@POLE_RELAMP_DATE DATE,
@POLE_HOUSE_NUM NUMERIC(4),
@POLE_STREET VARCHAR(50),
@POLE_FOUNDATION VARCHAR(30),
@POLE_HAS_FUSE BIT,
@POLE_ROAD_TYPE CHAR(1),
@POLE_NEAR_BUS_STOP BIT,
@POLE_NEAR_SCHOOL BIT,
@POLE_NEAR_PARK BIT,
@POLE_NEAR_SIDEWALK BIT,
@POLE_HAS_BANNER_ARMS BIT,
@POLE_X_COORD NUMERIC(8,5),
@POLE_Y_COORD NUMERIC(8,5)
AS
BEGIN
INSERT INTO POLE VALUES (
@POLE_ID,
@POLE_IS_LIGHT_POLE,
@POLE_IS_TRAFFIC_POLE,
@POLE_COMMENTS,
@POLE_LAST_INSPECTION_DATE,
@POLE_HEIGHT,
@POLE_COLOUR,
@POLE_REPAINT_DATE,
@POLE_INSTALL_DATE,
@POLE_REMOVED,
@POLE_LIGHT_TYPE,
@POLE_BULB_TYPE,
@POLE_WATTAGE,
@POLE_RELAMP_DATE,
@POLE_HOUSE_NUM,
@POLE_STREET,
@POLE_FOUNDATION,
@POLE_HAS_FUSE,
@POLE_ROAD_TYPE,
@POLE_NEAR_BUS_STOP,
@POLE_NEAR_SCHOOL,
@POLE_NEAR_PARK,
@POLE_NEAR_SIDEWALK,
@POLE_HAS_BANNER_ARMS,
@POLE_X_COORD,
@POLE_Y_COORD);
END
GO

CREATE PROCEDURE INSERT_TRAFFIC_POLE
@POLE_ID NUMERIC(8),
@POLE_IS_LIGHT_POLE BIT,
@POLE_IS_TRAFFIC_POLE BIT,
@POLE_COMMENTS VARCHAR(255),
@POLE_LAST_INSPECTION_DATE DATE,
@POLE_HEIGHT NUMERIC(3, 1),
@POLE_COLOUR VARCHAR(20),
@POLE_REPAINT_DATE DATE,
@POLE_INSTALL_DATE DATE,
@POLE_REMOVED BIT,
@POLE_LIGHT_TYPE VARCHAR(3),
@POLE_BULB_TYPE VARCHAR(3),
@POLE_WATTAGE NUMERIC(4),
@POLE_RELAMP_DATE DATE,
@POLE_HOUSE_NUM NUMERIC(4),
@POLE_STREET VARCHAR(50),
@POLE_FOUNDATION VARCHAR(30),
@POLE_HAS_FUSE BIT,
@POLE_ROAD_TYPE CHAR(1),
@POLE_NEAR_BUS_STOP BIT,
@POLE_NEAR_SCHOOL BIT,
@POLE_NEAR_PARK BIT,
@POLE_NEAR_SIDEWALK BIT,
@POLE_HAS_BANNER_ARMS BIT,
@POLE_X_COORD NUMERIC(8,5),
@POLE_Y_COORD NUMERIC(8,5),
@POLE_PUSH_BUTTON BIT,
@POLE_SIGNAL_DIRECTION VARCHAR(2),
@POLE_SIGNAGE VARCHAR(30)
AS
BEGIN
EXEC INSERT_POLE
@POLE_ID,
@POLE_IS_LIGHT_POLE,
@POLE_IS_TRAFFIC_POLE,
@POLE_COMMENTS,
@POLE_LAST_INSPECTION_DATE,
@POLE_HEIGHT,
@POLE_COLOUR,
@POLE_REPAINT_DATE,
@POLE_INSTALL_DATE,
@POLE_REMOVED,
@POLE_LIGHT_TYPE,
@POLE_BULB_TYPE,
@POLE_WATTAGE,
@POLE_RELAMP_DATE,
@POLE_HOUSE_NUM,
@POLE_STREET,
@POLE_FOUNDATION,
@POLE_HAS_FUSE,
@POLE_ROAD_TYPE,
@POLE_NEAR_BUS_STOP,
@POLE_NEAR_SCHOOL,
@POLE_NEAR_PARK,
@POLE_NEAR_SIDEWALK,
@POLE_HAS_BANNER_ARMS,
@POLE_X_COORD,
@POLE_Y_COORD
INSERT INTO TRAFFIC_POLE VALUES (@POLE_ID, @POLE_PUSH_BUTTON, @POLE_SIGNAL_DIRECTION, @POLE_SIGNAGE);
END
GO

CREATE PROCEDURE INSERT_LIGHT_POLE
@POLE_ID NUMERIC(8),
@POLE_IS_LIGHT_POLE BIT,
@POLE_IS_TRAFFIC_POLE BIT,
@POLE_COMMENTS VARCHAR(255),
@POLE_LAST_INSPECTION_DATE DATE,
@POLE_HEIGHT NUMERIC(3, 1),
@POLE_COLOUR VARCHAR(20),
@POLE_REPAINT_DATE DATE,
@POLE_INSTALL_DATE DATE,
@POLE_REMOVED BIT,
@POLE_LIGHT_TYPE VARCHAR(3),
@POLE_BULB_TYPE VARCHAR(3),
@POLE_WATTAGE NUMERIC(4),
@POLE_RELAMP_DATE DATE,
@POLE_HOUSE_NUM NUMERIC(4),
@POLE_STREET VARCHAR(50),
@POLE_FOUNDATION VARCHAR(30),
@POLE_HAS_FUSE BIT,
@POLE_ROAD_TYPE CHAR(1),
@POLE_NEAR_BUS_STOP BIT,
@POLE_NEAR_SCHOOL BIT,
@POLE_NEAR_PARK BIT,
@POLE_NEAR_SIDEWALK BIT,
@POLE_HAS_BANNER_ARMS BIT,
@POLE_X_COORD NUMERIC(8,5),
@POLE_Y_COORD NUMERIC(8,5),
@POLE_STYLE VARCHAR(30),
@POLE_LUMINAIR_STYLE VARCHAR(30),
@POLE_BASE_COLLAR BIT
AS
BEGIN
EXEC INSERT_POLE
@POLE_ID,
@POLE_IS_LIGHT_POLE,
@POLE_IS_TRAFFIC_POLE,
@POLE_COMMENTS,
@POLE_LAST_INSPECTION_DATE,
@POLE_HEIGHT,
@POLE_COLOUR,
@POLE_REPAINT_DATE,
@POLE_INSTALL_DATE,
@POLE_REMOVED,
@POLE_LIGHT_TYPE,
@POLE_BULB_TYPE,
@POLE_WATTAGE,
@POLE_RELAMP_DATE,
@POLE_HOUSE_NUM,
@POLE_STREET,
@POLE_FOUNDATION,
@POLE_HAS_FUSE,
@POLE_ROAD_TYPE,
@POLE_NEAR_BUS_STOP,
@POLE_NEAR_SCHOOL,
@POLE_NEAR_PARK,
@POLE_NEAR_SIDEWALK,
@POLE_HAS_BANNER_ARMS,
@POLE_X_COORD,
@POLE_Y_COORD
INSERT INTO LIGHT_POLE VALUES (@POLE_ID, @POLE_STYLE, @POLE_LUMINAIR_STYLE, @POLE_BASE_COLLAR);
END
GO

CREATE PROCEDURE INSERT_COMBINATION_POLE
@POLE_ID NUMERIC(8),
@POLE_IS_LIGHT_POLE BIT,
@POLE_IS_TRAFFIC_POLE BIT,
@POLE_COMMENTS VARCHAR(255),
@POLE_LAST_INSPECTION_DATE DATE,
@POLE_HEIGHT NUMERIC(3, 1),
@POLE_COLOUR VARCHAR(20),
@POLE_REPAINT_DATE DATE,
@POLE_INSTALL_DATE DATE,
@POLE_REMOVED BIT,
@POLE_LIGHT_TYPE VARCHAR(3),
@POLE_BULB_TYPE VARCHAR(2),
@POLE_WATTAGE NUMERIC(4),
@POLE_RELAMP_DATE DATE,
@POLE_HOUSE_NUM NUMERIC(4),
@POLE_STREET VARCHAR(50),
@POLE_FOUNDATION VARCHAR(30),
@POLE_HAS_FUSE BIT,
@POLE_ROAD_TYPE CHAR(1),
@POLE_NEAR_BUS_STOP BIT,
@POLE_NEAR_SCHOOL BIT,
@POLE_NEAR_PARK BIT,
@POLE_NEAR_SIDEWALK BIT,
@POLE_HAS_BANNER_ARMS BIT,
@POLE_X_COORD NUMERIC(8,5),
@POLE_Y_COORD NUMERIC(8,5),
@POLE_PUSH_BUTTON BIT,
@POLE_SIGNAL_DIRECTION VARCHAR(2),
@POLE_SIGNAGE VARCHAR(30),
@POLE_STYLE VARCHAR(30),
@POLE_LUMINAIR_STYLE VARCHAR(30),
@POLE_BASE_COLLAR BIT
AS
BEGIN
EXEC INSERT_POLE
@POLE_ID,
@POLE_IS_LIGHT_POLE,
@POLE_IS_TRAFFIC_POLE,
@POLE_COMMENTS,
@POLE_LAST_INSPECTION_DATE,
@POLE_HEIGHT,
@POLE_COLOUR,
@POLE_REPAINT_DATE,
@POLE_INSTALL_DATE,
@POLE_REMOVED,
@POLE_LIGHT_TYPE,
@POLE_BULB_TYPE,
@POLE_WATTAGE,
@POLE_RELAMP_DATE,
@POLE_HOUSE_NUM,
@POLE_STREET,
@POLE_FOUNDATION,
@POLE_HAS_FUSE,
@POLE_ROAD_TYPE,
@POLE_NEAR_BUS_STOP,
@POLE_NEAR_SCHOOL,
@POLE_NEAR_PARK,
@POLE_NEAR_SIDEWALK,
@POLE_HAS_BANNER_ARMS,
@POLE_X_COORD,
@POLE_Y_COORD
INSERT INTO TRAFFIC_POLE VALUES (@POLE_ID, @POLE_PUSH_BUTTON, @POLE_SIGNAL_DIRECTION, @POLE_SIGNAGE);
INSERT INTO LIGHT_POLE VALUES (@POLE_ID, @POLE_STYLE, @POLE_LUMINAIR_STYLE, @POLE_BASE_COLLAR);
END
GO

CREATE TRIGGER UPDATE_MANAGERS
ON DEPARTMENT_MANAGER
AFTER INSERT, UPDATE 
AS
UPDATE DEPARTMENT
SET MGR_ID = EMPLOYEE.EMP_ID
FROM EMPLOYEE
WHERE EMPLOYEE.EMP_TYPE = 'MGR' AND EMPLOYEE.DPT_CODE = DEPARTMENT.DPT_CODE;
GO


--Create triggers
CREATE TRIGGER NEW_REPORT
ON INSPECTION_REPORT
AFTER INSERT
AS
UPDATE POLE
SET Pole.POLE_LAST_INSPECTION_DATE = SYSDATETIME()
FROM INSPECTION_REPORT
WHERE POLE.POLE_ID = INSPECTION_REPORT.POLE_ID;
GO

--Create managers and departments
INSERT INTO DEPARTMENT VALUES(001, 'Engineering Department', NULL);
INSERT INTO DEPARTMENT VALUES(002, 'Planning Department', NULL);
INSERT INTO DEPARTMENT VALUES(003, 'Field Technician Department', NULL);
EXEC INSERT_DEPARTMENT_MANAGER 0004, 'Field Technician Manager', 'Big', 'mcLargeHuge', '604-423-7349', 003, 'MGR', NULL, NULL;
EXEC INSERT_DEPARTMENT_MANAGER 0002, 'Planning Manager', 'Shrek', 'Swampworth', '604-421-6353', 002, 'MGR', NULL, NULL;
EXEC INSERT_DEPARTMENT_MANAGER 0005, 'Engineering Manager', 'Robert', 'LeConstructeur', '604-424-6259', 001, 'MGR', NULL, NULL;
GO

--Populate employees table
EXEC INSERT_ENGINEER 0001, 'Pole Engineer', 'Geoff', 'Geofferson', '604-420-6324', 001, 'ENG', 'Electrical Engineer';
EXEC INSERT_PLANNER 0003, 'Planner 2', 'Anton', 'Barton', '604-420-1253', 002, 'PLN', 'City Planner';
EXEC INSERT_FIELD_TECHNICIAN 0006, 'Junior Field Technician', 'Barnaby', 'Davies', '604-420-6982', 003, 'FTC', 'North Side';
EXEC INSERT_FIELD_TECHNICIAN 0007, 'Junior Field Technician', 'Albus', 'Scott', '604-420-2634', 003, 'FTC', 'South Side';
EXEC INSERT_FIELD_TECHNICIAN 0008, NULL, 'Albus', 'Scott', '604-420-5123', 003, 'FTC', 'North Side';
EXEC INSERT_FIELD_TECHNICIAN 0009, 'Intermediate Field Technician', 'Samantha', 'Leyore', '604-420-9532', 003, 'FTC', 'South Side';
EXEC INSERT_FIELD_TECHNICIAN 0010, 'Senior Field Technician', 'Jan', 'Dickinson', '604-420-1522', 003, 'FTC', 'Whiterock';

--Populate poles table
EXEC INSERT_LIGHT_POLE 1, 1, 0, 'group relamp/repaint/new breakers and contactor', '2020-09-30', 7.5, 'black', '2015-09-14', '1997-01-01', 0, 'L', 'HPS', 150, '2004-03-25', 1101, 'Jordan Dr', 'square', 0, 'Y', 0, 0, 0, 0, 0, -122.8428496, 49.82846642, 'Single Davit', 'Cobra Head', 0;
EXEC INSERT_LIGHT_POLE 2, 1, 0, 'no anchor bolt caps', '2018-02-12', 7.5, 'black', '2016-04-18', '1997-03-08', 0, 'LMF', 'HPS', 150, '2016-04-18', 1348, 'Station Dr', 'square', 0, 'Y', 0, 1, 0, 1, 0, -121.8428496, 49.92846642, 'Single Davit', 'Decorative', 0;
EXEC INSERT_LIGHT_POLE 3, 1, 0, 'new ballast', '2018-07-05', 8, 'green', '2018-04-18', '1999-07-11', 1, 'LMB', 'LED', 250, '2018-04-18', 1352, 'Marina Ave', 'square', 0, 'Y', 0, 0, 1, 1, 1, -123.8428496, 49.32846642, 'Double Davit', 'Domus', 1;
EXEC INSERT_LIGHT_POLE 4, 1, 0, 'small dent at 19 inch and larger at 39 inch height', '2020-10-12', 9, 'silver', '2011-09-11', '2001-01-01', 0, 'L', 'LED', 250, '2011-03-22', 1110, 'Bueno Noche St', 'round', 1, 'Y', 0, 1, 1, 0, 0, -120.8428496, 49.22846642, 'Decorative', 'Cobra Head', 0;
EXEC INSERT_TRAFFIC_POLE 5, 0, 1, 'minor graffiti', '2015-11-11', 7.5, 'silver', '2011-03-22', '2004-01-11', 0, 'L', 'LED', 250, '2011-03-22', 2630, 'Marina Ave', 'round', 1, 'Y', 0, 1, 1, 1, 0, -120.67428496, 49.22846642, 1, 'N', 'One way';
EXEC INSERT_TRAFFIC_POLE 6, 0, 1, 'wb primary, nw corner', '2019-10-24', 8, 'black', '2012-07-12', '2005-02-26', 0, 'LMF', 'HPS', 200, '2012-07-12', 3450, 'Jordan Dr', 'square', 0, 'Y', 1, 1, 1, 0, 1, -120.3528496, 49.22846642, 0, 'E', 'Yield';
EXEC INSERT_TRAFFIC_POLE 7, 0, 1, 'wb primary ts', '2018-09-24', 9, 'silver', '2013-03-14', '2006-03-14', 0, 'L', 'HPS', 150, '2013-03-14', 6580, 'Bueno Noche St', 'round', 0, 'Y', 1, 1, 0, 1, 0, -120.1528496, 49.22846642, 1, 'S', 'Stop';
EXEC INSERT_TRAFFIC_POLE 8, 0, 1, 'wb secondary traffic pole', '2017-08-24', 9, 'green', '2014-08-08', '2007-04-30', 0, 'LMB', 'LED', 150, '2014-08-08', 1250, 'Bueno Noche St', 'square', 1, 'Y', 0, 1, 1, 0, 1, -120.1628496, 49.22846642, 1, 'W', 'Stop';
EXEC INSERT_COMBINATION_POLE 9, 1, 1, 'dented pole, missing anchor bolt caps', '2018-08-24', 7.5, 'black', '2013-12-20', '2006-06-06', 0, 'LMB', 'LED', 150, '2013-02-19', 1460, 'Jordan Dr', 'round', 1, 'Y', 0, 1, 1, 0, 1, -121.1628496, 48.22846642, 1, 'W', 'Stop', 'Single Davit', 'Domus', 0;
EXEC INSERT_COMBINATION_POLE 10, 1, 1, 'bc hydro metered, public wr north storage', '2019-08-24', 7.5, 'black', '2017-11-24', '2004-05-05', 1, 'LMF', 'HPS', 250, '2016-04-01', 1780, 'Bueno Noche St', 'square', 0, 'Y', 1, 0, 1, 1, 1, -119.1628496, 50.22846642, 1, 'N', 'One Way', 'Double Davit', 'Decorative', 1;

--Populate Inspection reports
INSERT INTO INSPECTION_REPORT VALUES(1, 0006, 2, '2020-02-26', 'Poor paint/flaking', 'Condition Assessment 2020', 37, 2, 3, 'Good', 2, 0, 1, 0, 2);
INSERT INTO INSPECTION_REPORT VALUES(2, 0006, 1, '2020-09-11', 'Visble holes', 'Condition Assessment 2020', 35, 2, 3, 'Good', 1, 0, 1, 0, 2);
INSERT INTO INSPECTION_REPORT VALUES(3, 0006, 10, '2019-12-08', 'Poor paint/flaking', 'Condition Assessment 2019', 40, 3, 3, 'Good', 3, 0, 1, 1, 3);
INSERT INTO INSPECTION_REPORT VALUES(4, 0007, 10, '2020-08-24', 'Visble holes', 'Condition Assessment 2020', 38, 3, 1, 'Good', 3, 0, 1, 1, 3);
INSERT INTO INSPECTION_REPORT VALUES(5, 0006, 5, SYSDATETIME(), 'Poor paint/flaking', 'Condition Assessment 2020', 34, 3, 3, 'Good', 2, 1, 1, 0, 1);
INSERT INTO INSPECTION_REPORT VALUES(6, 0001, 6, SYSDATETIME(), 'Visible Rust', 'Condition Assessment 2020', 41, 1, 2, 'Poor', 3, 1, 0, 1, 2);
INSERT INTO INSPECTION_REPORT VALUES(7, 0009, 7, SYSDATETIME(), 'Visble holes', 'Condition Assessment 2020', 39, 1, 1, 'Good', 3, 0, 1, 1, 3);
